### ISSUE TITLE
Unknown URL schema

### ISSUE THREAD

**Issue by marines** [auth0-samples/auth0-cordova-samples#15] opened 2017-08-26 09:57 UTC
The example doesn't work for me. I'm getting the following error after logging in with Google oauth:

![media-20170826](https://user-images.githubusercontent.com/78715/29740393-c0c2f0d6-8a55-11e7-83c0-8793ee321e66.png)

**Comment by miketrebilcock** [comment] 2017-09-19 11:35
Struggling with the same issue. Some advice here - https://community.auth0.com/questions/3319/ionic-2-err-unknown-url-scheme but none of it has fixed it for me.

**Comment by JohnMcLear** [comment] 2017-12-04 09:08
Sample works for me.

**Comment by christiphercalder** [comment] 2018-05-28 19:56
Having this issue as well but only on Android platform, iOS is working correctly.
Has anyone found a fix for this on Android?

**Comment by davidpatrick** [comment] 2020-02-20 19:55
Sorry for the delay on getting back to you on this. This was previously maintained by the Auth0 Community, and now our SDKs team has taken over responsibility for this repo.

It looks like this issue is associated with https://github.com/EddyVerbruggen/Custom-URL-scheme/releases/tag/5.0.0 -- We are bumping this dependency here https://github.com/auth0-samples/auth0-cordova-samples/pull/42

Let me know if this doesn't solve everyones issue, as I am unable to reproduce the problem in the thread.

**Closed** 2020-02-20 20:04 UTC
Labels: bug, difficulty: medium, help wanted
